AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LoggingFunction
      Handler: logging.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          RDS_HOSTNAME: yourhostname_and_port
          RDS_DB_NAME:  logs
          RDS_USERNAME: dbuser
          RDS_PASSWORD: mypassword
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /log
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoggingApi:
    Description: "API Gateway endpoint URL for Prod stage for logging function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/log/"
  LoggingFunction:
    Description: "Logging Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  LoggingFunctionIamRole:
    Description: "Implicit IAM Role created for Logging function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
